server:
  port: 8002

spring:
  profiles:
    active: dev

  application:
    name: cloud-payment-service



swagger:
  base-package: com.heyx.springcloud.route
  base-path: /api/**
  title: springcloud
  description: v1.0.0
  termsOfServiceUrl: /
  version: 1.0


mybatis-plus:
  mapper-locations: classpath:com/heyx/springcloud/mapper/**/*.xml
  type-aliases-package: com.heyx.springcloud.entity
  configuration:
    map-underscore-to-camel-case: true #采用驼峰命名 映射下划线字段配置

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: payment8002
    prefer-ip-address: true