server:
  port: 8083

swagger:
  base-package: com.heyx.springcloud.route
  base-path: /api/**
  title: springcloud
  description: v1.0.0
  termsOfServiceUrl: /
  version: 1.0


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service-url:
  nacos-user-service: http://nacos-payment-provider