spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heyx_spring_cloud?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

    druid:
      initialSize: 5
      maxActive: 10
      maxWait: 3000
      minIdle: 3
      test-on-borrow: false
      test-while-idle: false
      test-on-return: false