server:
  port: 8001

spring:
  profiles:
    active: dev

  application:
    name: cloud-payment-service
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver

swagger:
  base-package: com.heyx.springcloud.route
  base-path: /api/**
  title: springcloud
  description: v1.0.0
  termsOfServiceUrl: /
  version: 1.0



mybatis-plus:
  mapper-locations: classpath*:com/heyx/springcloud/dao/**/*.xml
  type-aliases-package: com.heyx.springcloud.entity
  configuration:
    map-underscore-to-camel-case: true #采用驼峰命名 映射下划线字段配置

