server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:58848
    sentinel:
      transport:
        dashboard: 127.0.0.1:58080
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'